// JobKind.ts

export const JOB_CATEGORIES = [
  {
    name: "IT·개발",
    roles: [
      { name: "전체" },
      { name: "서버·백엔드" },
      { name: "프론트엔드" },
      { name: "웹풀스택" },
      { name: "안드로이드" },
      { name: "iOS" },
      { name: "크로스 플랫폼" },
      { name: "DBA" },
      { name: "DevOps·SRE" },
      { name: "시스템·네트워크" },
      { name: "시스템소프트웨어" },
      { name: "소프트웨어 엔지니어" },
      { name: "정보보호·보안" },
      { name: "임베디드 소프트웨어" },
      { name: "로봇SW" },
      { name: "QA·테스트" },
      { name: "사물인터넷(IoT)" },
      { name: "응용 프로그램" },
      { name: "블록체인" },
      { name: "개발PM" },
      { name: "웹 퍼블리싱" },
      { name: "VR·AR·3D" },
      { name: "ERP·SAP" },
      { name: "그래픽스" },
      { name: "하드웨어엔지니어" },
      { name: "기타IT·개발" },
    ],
  },
  {
    name: "AI·데이터",
    roles: [
      { name: "전체" },
      { name: "데이터 분석가" },
      { name: "데이터 사이언티스트" },
      { name: "데이터 엔지니어" },
      { name: "머신러닝 엔지니어" },
      { name: "멀티모달엔지니어" },
      { name: "생성형AI" },
      { name: "영상·음성AI" },
      { name: "자율주행" },
      { name: "컴퓨터 비전" },
      { name: "AI 비즈니스" },
      { name: "AI 서비스 기획" },
      { name: "AI리서치" },
      { name: "NLP" },
      { name: "LLM" },
      { name: "MLOps" },
      { name: "RAG" },
      { name: "기타AI·데이터" },
    ],
  },
  {
    name: "게임",
    roles: [
      { name: "전체" },
      { name: "게임기획·PM" },
      { name: "게임운영" },
      { name: "게임QA" },
      { name: "게임개발(클라이언트)" },
      { name: "게임개발(서버)" },
      { name: "게임개발(모바일)" },
      { name: "테크니컬아티스트" },
      { name: "게임아트" },
      { name: "게임3D모델링" },
      { name: "게임애니메이션" },
      { name: "게임이펙트·FX" },
      { name: "게임인터페이스" },
      { name: "게임연출·영상" },
      { name: "게임사운드" },
      { name: "기타게임" },
    ],
  },
  {
     name: "디자인",
  roles: [
    { name: "전체" },
    { name: "UIUX·프로덕트" },
    { name: "웹디자인" },
    { name: "디자인리서치" },
    { name: "그래픽·시각" },
    { name: "일러스트레이터" },
    { name: "브랜딩·BIBX" },
    { name: "공간·실내·VMD" },
    { name: "산업(제품)" },
    { name: "패키지" },
    { name: "광고·콘텐츠" },
    { name: "영상·모션" },
    { name: "3D·VFX" },
    { name: "출편·편집" },
    { name: "건축·공공·조경디자인" },
    { name: "패션·텍스타일" },
    { name: "기타디자인" },
  ],
  },
  {
  name: "기획·전략",
  roles: [
    { name: "전체" },
    { name: "PM·PO" },
    { name: "서비스·상품기획" },
    { name: "사업·전략계획" },
    { name: "컨설팅" },
    { name: "기술계획" },
    { name: "사업개발·분석" },
    { name: "프로젝트 매니저" },
    { name: "운영관리(OM)" },
    { name: "경영지원" },
    { name: "기타기획·전략·경영" },
  ],
},

  {
  name: "마케팅·광고",
  roles: [
    { name: "전체" },
    { name: "마케팅기획·전략" },
    { name: "퍼포먼스 마케팅" },
    { name: "콘텐츠마케팅" },
    { name: "SNS마케팅" },
    { name: "브랜드 마케팅" },
    { name: "CRM마케팅" },
    { name: "글로벌 마케팅" },
    { name: "광고기획(AE)" },
    { name: "홍보·PR" },
    { name: "전시·행사·마케팅" },
    { name: "기타마케팅" },
  ],
},

  {
  name: "상품기획·MD",
  roles: [
    { name: "전체" },
    { name: "상품기획" },
    { name: "온라인MD" },
    { name: "식품MD" },
    { name: "패션MD" },
    { name: "뷰티MD" },
    { name: "영업MD" },
    { name: "리테일MD" },
    { name: "기타상품기획·MD" },
  ],
},
  {
  name: "영업",
  roles: [
    { name: "전체" },
    { name: "B2C영업" },
    { name: "B2B영업" },
    { name: "영업관리·지원" },
    { name: "일반영업" },
    { name: "기술·IT영업" },
    { name: "금융·보험영업" },
    { name: "해외영업" },
    { name: "제약·의료영업" },
    { name: "기타 영업" },
  ],
},

  {
  name: "무역·물류",
  roles: [
    { name: "전체" },
    { name: "해외·상사영업" },
    { name: "수출입관리·사무" },
    { name: "관세사" },
    { name: "무역금융" },
    { name: "포워딩" },
    { name: "구매·조달" },
    { name: "물류·SCM" },
    { name: "입출고·포장" },
    { name: "자재·재고관리" },
    { name: "운송" },
    { name: "유통관리" },
    { name: "설비·시설관리" },
    { name: "기타무역·물류·유통" },
  ],
},

  {
  name: "운송·배송",
  roles: [
    { name: "전체" },
    { name: "배송·배달" },
    { name: "승객운송" },
    { name: "물류운송" },
    { name: "전문운전" },
    { name: "배차관리" },
    { name: "기타운전·운송" },
  ],
},

  {
  name: "법률법무",
  roles: [
    { name: "전체" },
    { name: "변호사" },
    { name: "변리사" },
    { name: "법무" },
    { name: "컴플라이언스" },
    { name: "내부감사" },
    { name: "ESG·윤리" },
    { name: "특허·IP" },
    { name: "기타법률" },
  ],
},

  {
  name: "HR·총무",
  roles: [
    { name: "전체" },
    { name: "인사기획" },
    { name: "평가·보상" },
    { name: "HRD·조직문화" },
    { name: "리크루터·헤드헌터" },
    { name: "노무관리" },
    { name: "총무·비서" },
    { name: "기타 HR·총무" },
  ],
},

  {
  name: "회계·재무·세무",
  roles: [
    { name: "전체" },
    { name: "회계" },
    { name: "재무" },
    { name: "세무" },
    { name: "IR·공시" },
    { name: "경리·회계보조" },
    { name: "기타회계·재무·세무" },
  ],
},

{
  name: "증권·운용",
  roles: [
    { name: "전체" },
    { name: "운용·트레이닝" },
    { name: "리스크·준법·심사" },
    { name: "VC·PE" },
    { name: "증권IB" },
    { name: "부동산·인프라금융" },
    { name: "PB·WM" },
    { name: "경영지원·관리" },
    { name: "금융상품개발·영업" },
    { name: "기타증권·운용" },
  ],
},

  {
  name: "은행·카드·보험",
  roles: [
    { name: "전체" },
    { name: "은행" },
    { name: "카드사" },
    { name: "캐피탈" },
    { name: "보험설계" },
    { name: "계리" },
    { name: "손해사정" },
    { name: "언더라이팅·심사" },
    { name: "청구·보상" },
    { name: "보험상품개발" },
    { name: "기타은행·보험" },
  ],
},

  {
  name: "엔지니어링·R&D",
  roles: [
    { name: "전체" },
    { name: "반도체·디스플레이" },
    { name: "전기·전자·제어" },
    { name: "통신기술·네트워크구축" },
    { name: "기계" },
    { name: "기계설계·CAD" },
    { name: "자동차" },
    { name: "조선·항공·우주" },
    { name: "금속·철강" },
    { name: "화학" },
    { name: "화장품" },
    { name: "바이오·제약" },
    { name: "식품" },
    { name: "에너지" },
    { name: "환경" },
    { name: "기타엔지니어링·R&D" },
  ],
},

{
  name: "건설·건축",
  roles: [
    { name: "전체" },
    { name: "건축설계·시공" },
    { name: "토목·측량·조경·환경" },
    { name: "기계·전기·소방·설비" },
    { name: "설계·감리·시공·공무" },
    { name: "안전·품질·재료" },
    { name: "사무·관리·전산" },
    { name: "건설특수·일용직" },
    { name: "기타건설·건축" },
  ],
},
{
  name: "생산·기능직",
  roles: [
    { name: "전체" },
    { name: "생산" },
    { name: "공무" },
    { name: "설비" },
    { name: "환경안전" },
    { name: "물류" },
    { name: "품질" },
    { name: "건설·공사·프로젝트" },
    { name: "설계·CAD·CAM" },
    { name: "시설관리" },
    { name: "기타생산·기능직" },
  ],
},


 {
  name: "의료·보건",
  roles: [
    { name: "전체" },
    { name: "의사" },
    { name: "한의사" },
    { name: "수의사" },
    { name: "약사·약무보조" },
    { name: "간호사" },
    { name: "간호조무사" },
    { name: "치위생사" },
    { name: "응급구조사" },
    { name: "물리치료·작업치료" },
    { name: "영상의학·임상병리·검사" },
    { name: "영양사·임상영양사" },
    { name: "의료미용·에스테틱" },
    { name: "병원행정·접수·수납" },
    { name: "요양보호사" },
    { name: "조리원" },
    { name: "안경·검안사" },
    { name: "기타의료·보건" },
  ],
},

 {
  name: "공공·복지",
  roles: [
    { name: "전체" },
    { name: "행정·사무·운영" },
    { name: "기술·전산·시설" },
    { name: "복지·사회서비스" },
    { name: "교육·연구" },
    { name: "공공안전" },
    { name: "상담·심리" },
    { name: "종교" },
    { name: "아동·청소년복지" },
    { name: "노인·여성복지" },
    { name: "자원봉사" },
    { name: "기타공공·복지" },
  ],
},

{
  name: "교육",
  roles: [
    { name: "전체" },
    { name: "유치원·보육교사" },
    { name: "기간제·사립교사" },
    { name: "방과후·사립교사" },
    { name: "대학교수·강사" },
    { name: "교직원·조교" },
    { name: "입시학원강사" },
    { name: "국어·외국어강사" },
    { name: "기술·전문강사" },
    { name: "학습지·방문교사" },
    { name: "학원상담·운영" },
    { name: "교재개발·교수설계" },
    { name: "기타교육" },
  ],
},

{
  name: "미디어·엔터",
  roles: [
    { name: "전체" },
    { name: "PD·감독" },
    { name: "콘텐츠기획·에디터" },
    { name: "방송작가" },
    { name: "촬영감독·카메라" },
    { name: "영상편집" },
    { name: "CG·모션그래픽" },
    { name: "사운드디자이너" },
    { name: "기자·리포터" },
    { name: "아나운서·쇼호스트" },
    { name: "성우·나래이터" },
    { name: "크리에이터·인플루엔서" },
    { name: "모델·연기자" },
    { name: "사진작가" },
    { name: "방송기술·중계" },
    { name: "송출·편성" },
    { name: "아티스트매니지먼트" },
    { name: "배급·제작사" },
    { name: "음원·음반" },
    { name: "웹툰·웹소설" },
    { name: "출판" },
    { name: "통·번역" },
    { name: "기타 미디어·엔터" },
  ],
},

  {
  name: "고객상담·TM",
  roles: [
    { name: "전체" },
    { name: "인바운드" },
    { name: "아웃바운드" },
    { name: "CS" },
    { name: "CX매니저" },
    { name: "기타고객상담" },
  ],
},

  {
  name: "서비스",
  roles: [
    { name: "전체" },
    { name: "설치·수리기사" },
    { name: "주차·주유" },
    { name: "가사도우미" },
    { name: "애견미용·훈련" },
    { name: "경호·경비" },
    { name: "호텔서비스" },
    { name: "관광서비스" },
    { name: "항공서비스" },
    { name: "매장운영·관리" },
    { name: "안내·리셉션" },
    { name: "헤어디자이너" },
    { name: "메이크업·네일" },
    { name: "피부관리" },
    { name: "마사지·체형관리" },
    { name: "웨딩플래너" },
    { name: "환경미화원" },
    { name: "기타서비스" },
  ],
},

  {
  name: "식음료",
  roles: [
    { name: "전체" },
    { name: "식품가공·개발" },
    { name: "주방조리" },
    { name: "제과·제빵" },
    { name: "음료·주류" },
    { name: "매장운영·관리" },
    { name: "서비스·홀스태프" },
    { name: "식음컨설팅·지원" },
    { name: "기타식음료" },
  ],
},

];
