import localFont from "next/font/local";
import Header from "@/components/widgets/Header";
import Footer from "@/components/widgets/Footer";
import ReactQueryProvider from "@/context/ReactQueryProvider";
import type { Metadata } from "next";
import "./globals.css";

const pretendard = localFont({
  src: "../../public/fonts/woff2/PretendardVariable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${pretendard.variable} antialiased`}>
        <ReactQueryProvider>
          <main className="tablet:px-6 flex flex-col items-center justify-center px-4">
            <Header />
            {children}
          </main>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
